version: '3.8'
services:
  app:
    build: 
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/client
    image: app:react
    container_name: socialito-React-container
    command: npm start